---
title: "Proyecto Probabilidad y Estadistica Primer Corte"
subtitle: 'Universidad de la Sabana'
author: "Andrea Forero - Juan Dimate - Caren Piñeros - Santiago Santafe"
output: rmdformats::downcute
---


## Introducción
El transporte tiene un papel crucial en la vida diaria de cada persona además que es fundamental en ciudades y comunidades. Un factor primordial es la accesibilidad, la comodidad y la eficiencia del transporte ya que pueden tener un impacto significativo en los individuos. Teniendo en cuenta esto, es importante comprender cómo diferentes grupos demográficos, incluído el género, experimentan y se relacionan con los sistemas de transporte.
El presente informe proporciona información de la correlación entre el género, el uso y la conformidad que se tienen con el transporte. Por medio de una meticulosa toma de datos buscamos analizar las percepciones y preferencias de hombres y mujeres frente al transporte teniendo en cuenta su día a día.
Se proporcionará un reporte detallado a lo largo de este informe de los datos obtenidos, los examinaremos y explicaremos las implicaciones de los datos obtenidos.


## Objetivo General
Investigar y analizar la correlación y repercusiones entre el genero y la preferencia del transporte público y la conformidad con este. A través de una encuesta diseñada específicamente para este propósito, buscamos comprender como los géneros lo perciben.

Objetivos específicos
•	Evaluar las preferencias de transporte de hombres y mujeres.
•	Determinar las razones detrás de las elecciones de transporte incluyendo diferentes factores.
•	Analizar si existen diferencias significativas entre la perspectiva de hombres y mujeres.


## Justificación
Es fundamental comprender como el genero puede influir en percepción de las cosas y situaciones del común, una de ellas es el transporte, los hábitos de uso y la satisfacción en este son esenciales para servicios más eficaces. Existen anécdotas, experiencias y estudios que son evidencia de que el género influye bastante cuando se va a mostrar una perspectiva sobre algo. Para corroborar esto, es necesario realizar una investigación detallada y específica para comprender mejor estos comportamientos.

## Planteamiento del problema
La movilidad y los medios de transporte en ciudades tan extensas, agitadas y congestionadas resultan tener un papel crucial en la vida diaria de las personas. Dentro de las características que atañen a estos dos conceptos, movilidad y medios de transporte, se encuentra la comodidad y nivel de satisfacción que perciben los usuarios a lo largo de sus desplazamientos. Este es un punto que no solo afecta el bienestar instantáneo de las personas, sino que tiene repercusiones en la efectividad y productividad de las actividades que realizan. Por ello, se considera pertinente analizar cómo diferentes variables, tales como género, edad y tiempo usado en un recorrido, influyen en la elección y percepción de los medios de transporte empleados en los entornos urbanos.

## Marco Teórico

La movilidad urbana es un tema social y gubernamental que se ve afectada por factores como la economía, la salud pública, la política, el medio ambiente, la demografía, entre otros. Por lo que permite investigar cómo diferentes factores prevalecen en el momento de decidir el medio de transporte a usar y las percepciones que se tienen del mismo.
Según un artículo emitido por la Universidad de los Andes, las mujeres tienden a valorar la seguridad y accesibilidad en sus desplazamientos, mientras que para los hombres prevalece que los medios de transporte sean más rápidos y, de preferencia, deportivos. Así mismo, hay otros componentes, bien sea por necesidades o gustos, que determinan la preferencia y satisfacción percibida.
En cuanto a la ciudad de Bogotá, es una capital destacada como metrópolis que a pesar de que cuenta con diversos sistemas y medios de transporte, desde caminar o ir en bicicleta hasta sistemas de transporte masivo como Transmilenio, sostiene desafíos de movilidad muy grandes, congestión vial, calidad de servicio, accesibilidad, contaminación, etc. (Universidad El Bosque, s.f.). Lo que hace interesante entender como se desarrolla la sociedad en este ambiente y su perspectiva al respecto, además si existen diferencias significativas entre a las respuestas obtenidas.
Para ello, se llevó a cabo una encuesta en Forms a una muestra de 153 personas residentes en la ciudad de Bogotá con el fin de analizar las relaciones entre las diferentes variables.
Los resultados de este estudio proporcionarán información para llevar a cabo los objetivos propuestos.

## Tablas de frecuencias cruzadas o de contingencia
Las tablas de frecuencia cruzada o de contingencia, son estructuras utilizadas en estadística para organizar y resumir datos categóricos en términos de frecuencias de ocurrencia. Estas tablas constan de filas y columnas que representa las diferentes categóricas de dos o más variables. Las tablas de contingencia proporcionan una forma sistemática y visualmente comprensible de examinar la distribución conjunta de las categorías y detectar posibles patrones o tendencias en los datos.
Para crear tabla de frecuencia cruzada

`
tabla <- xtabs(~ Genero + Edad, data = datos)
print(tabla)`

## Variables
incluidas junto con su clasificación y su estadística descriptiva (presente las gráficas y resúmenes descriptivos que considere adecuados y que haya elaborado con R : Santiago

` dr = read_excel("ENCUESTA MOVILIDAD(1-154).xlsx") `
La variable dr lee el excel de los datos recopilados en la encuesta

` generos = table(dr$Genero) ` 
Hace una tabla de frecuencias a partir de las personas que respondieron y el genero que marcaron en la encuesta



## Resultados

El análisis de la proporción del medio de transporte por género en la encuesta revela disparidades significativas. Mientras que en el transporte privado se observa una distribución equitativa entre hombres y mujeres, con una cantidad similar haciendo uso de este medio, en cambio, en el transporte público, se evidencia una predominancia considerable de mujeres que usan este servicio en comparación con los hombres encuestados
Además, se destaca una marcada disparidad en los niveles de satisfacción entre los usuarios de transporte privado y público. Donde alrededor del 80% de los usuarios de transporte privado expresan estar entre completamente satisfechos o muy satisfechos con su tipo de transporte actual, en contraste con apenas el 32% de los usuarios de transporte público que reportan un nivel similar de satisfacción. Si profundizamos en el análisis de la satisfacción del sistema de transporte según el género y tipo de transporte, se observa que el 100% de los encuestados que manifestaron estar completamente satisfechos el servicio de transporte público son hombres. Además, se resalta que, en general, las mujeres muestran niveles de satisfacción menores frente a la contraparte masculina, tanto entre las usuarias del sistema de transporte público como entre aquellas que se movilizan en un vehículo particular.

El hecho de que las mujeres muestren niveles de satisfacción más bajos con el transporte público, a pesar de ser las principales usuarias de este servicio, puede tener una serie de efectos negativos en su vida cotidiana. Esta insatisfacción puede afectar su autonomía y calidad de vida. Además, el estrés y la ansiedad asociados con el uso del transporte público pueden tener un impacto negativo en su salud y bienestar emocional. Esta situación también contribuye a la perpetuación de desigualdades de género en la ciudad, ya que las mujeres pueden enfrentar barreras adicionales para participar plenamente en la vida urbana.

Por otra parte, es interesante notar que el metro es la opción ideal para la mayoría de los encuestados solo después del Carro particular, con un 21% frente a un 40%. Este interés en esta forma de transporte público  señala una posible alternativa para mejorar la movilidad en Bogotá. Sin embargo, es fundamental tener en cuenta que, para que el metro sea una opción verdaderamente efectiva, se debe considerar las necesidades y preocupaciones específicas de todos los grupos demográficos al planificar e implementar infraestructuras de transporte público en la ciudad.



## Conclusiones
Basado en los resultados de la encuesta, se observa una marcada disparidad de género en el uso y satisfacción del transporte en Bogotá. Aunque las mujeres representan la mayoría de los usuarios de este servicio, muestran niveles de satisfacción significativamente más bajos en comparación con los hombres. Esta discrepancia puede atribuirse, en parte, a la percepción de inseguridad y al acoso al que están expuestas mientras hacen uso del sistema de transporte masivo de la capital (Universidad Militar Nueva Granada).
Este ambiente de inseguridad y estrés presenciado en el transporte público puede tener consecuencias más amplias en la vida diaria de las mujeres. El estrés generado por estas situaciones puede afectar negativamente su bienestar emocional y mental, lo que a su vez puede dificultar su capacidad para concentrarse en sus responsabilidades cotidianas, como el trabajo, los estudios o el cuidado familiar. Además, el miedo constante a ser acosadas o agredidas puede llevar a las mujeres a evitar ciertas rutas de transporte o a buscar alternativas menos eficientes (Las Mujeres y el transporte en Bogotá:las cuentas, 2021), lo que limita su acceso a oportunidades y recursos en la ciudad.



## Bibliografía
Universidad de los Andes. (2023, 11 de julio). Movilidad de género: calidad de vida para las mujeres. Universidad de los Andes - Colombia - Sitio oficial. https://uniandes.edu.co/es/noticias/gobierno-y-politica/movilidad-de-genero-calidad-de-vida-para-las-mujeres

Universidad El Bosque. (s.f.). REVISTAS DE LA UNIVERSIDAD EL BOSQUE. https://revistas.unbosque.edu.co/index.php/RevTec/article/view/769/366

Las mujeres y el transporte en Bogotá: las cuentas. (2020). En Despacio.org. https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://despacio.org/portfolio/las-mujeres-y-el-transporte-en-bogota-las-cuentas/&ved=2ahUKEwjU-fGy1NCEAxVeHEQIHRO1A3kQFnoECB4QAQ&usg=AOvVaw2-3dfIVISG5OvFBjvbgmQU

https://www.ibm.com/docs/es/spss-statistics/saas?topic=tutorial-crosstabulation-tables#:~:text=Las%20tablas%20cruzadas%20(tablas%20de,una%20combinaci%C3%B3n%20exclusiva%20de%20valores

https://www.questionpro.com/blog/es/que-es-una-tabla-de-contingencia/


## Anexos
### Codigo Usado en R
``` {r} 
 library(readxl)
 library(ggplot2)
  library(dplyr)
library(knitr)
 dr = read_excel("ENCUESTA MOVILIDAD(1-154) (1).xlsx")
 kable(dr)
 #Borrar las columnas innecesarias generadas por Microsoft Forms
 dr = dr[, -c(1)]
 generos = table(dr$`Genero `)
 proporciones_Genero = prop.table(generos)
 
 # Crear un gráfico de torta para mostrar la proporción en genero
  proporciones_Genero=round(proporciones_Genero, 2)
  etiquetas = paste0(names(proporciones_Genero), ": ", proporciones_Genero * 100, "%")
  graficaGeneros = pie(proporciones_Genero, col = c("pink", "lightblue"), main = "Proporciones de Género", labels = etiquetas)


relacionMedioTrans_Genero = table(dr$`Genero `, dr$`¿Qué tipo transporte usa?`)
tabla_RelacionMedioTrans = as.data.frame(prop.table(relacionMedioTrans_Genero))
colnames(tabla_RelacionMedioTrans) <- c("Genero", "Tipo de transporte", "Porcentaje")
tabla_RelacionMedioTrans$Porcentaje <- round(tabla_RelacionMedioTrans$Porcentaje * 100, 2)
#Mostrar la grafica que muestre porcentajes entre medio de transporte y genero
kable(tabla_RelacionMedioTrans)
prop_relacionMedioTrans_Genero = prop.table(relacionMedioTrans_Genero)

barplot(prop_relacionMedioTrans_Genero, beside = TRUE, legend.text = TRUE, main = "Proporciones de Tipo de Medio de Transporte por Género", xlab = "Género", ylab = "Proporción")

# Calcular la proporción de Tipo de Medio de Transporte por Género
prop_relacionMedioTrans_Genero = prop.table(table(dr$`Genero `, dr$`¿Qué tipo transporte usa?`))



# Relación entre tipo de medio de transporte y género

ggplot(dr, aes(x = `¿Qué tipo transporte usa?`, fill = `Genero `)) +
  geom_bar(position = "dodge") +
  labs(
    x = "Tipo de Transporte",
    y = "Frecuencia") +
  scale_fill_manual(values = c("pink", "lightblue")) +
  theme_minimal()


#Relacion entre nivel de conformidad y tipo de medio de transporte

barplot(table(dr$'Nivel de conformidad',dr$'¿Qué tipo transporte usa?'),beside = TRUE, legend.text = TRUE,main = "Conformidad por tipo de medio de transporte",xlab = "Tipo de medio de transporte", ylab="Conformidad")



# Conformidad por tipo de transporte y género
ggplot(dr, aes(x = `¿Qué tipo transporte usa?`, fill = `Genero `)) +
  geom_bar(position = "dodge") +
  facet_wrap(~ `Nivel de conformidad`) +
  labs(
       x = "Tipo de Transporte",
       y = "Frecuencia") +
  scale_fill_manual(values = c("pink", "lightblue")) +
  theme_minimal()


# Calcular la frecuencia de cada tipo de transporte ideal

frecuencia_transporte_ideal <- table(dr$`Medio transporte ideal. ¿Por qué?`)

# Convertir la tabla en un dataframe
df_frecuencia <- as.data.frame(frecuencia_transporte_ideal)

# Renombrar las columnas
colnames(df_frecuencia) <- c("Transporte_Ideal", "Frecuencia")

# Crear el gráfico de torta
ggplot(df_frecuencia, aes(x = "", y = Frecuencia, fill = Transporte_Ideal)) +
  geom_bar(stat = "identity") +
  coord_polar("y", start = 0) +
  labs(title = "Distribución del Tipo de Transporte Ideal",
       fill = "Tipo de Transporte Ideal") +
  theme_minimal() +
  theme(legend.position = "bottom")

# Boxplot para analizar gastos promedios de dinero
bp <- boxplot(as.numeric(dr$`En promedio cuánto dinero gasta a diario, en transporte`), 
  main="Cajas y Bigotes de gastos", 
  xlab="Gastos", 
  horizontal=TRUE)

# Mostrar los valores de q1, q2 y q3
q1 <- bp$stats[2]
q2 <- bp$stats[3]
q3 <- bp$stats[4]

# Agregar las etiquetas al gráfico
legend("topright", inset=.05, title="Cuartiles", 
       legend=paste("Q1: ", round(q1, 2), "\nQ2: ", round(q2, 2), "\nQ3: ", round(q3, 2)), cex=1)

# Generar una tabla de contingencia para analizar la relación entre género y conformidad según el tiempo
tabla_contingencia <- table(dr$`Genero `, dr$`Nivel de conformidad`, cut(as.numeric(dr$`Tiempo que tarda en 1 recorrido (Minutos)`), breaks = 5))

# Crear un gráfico de barras apiladas para cada nivel de tiempo
for (i in 1:dim(tabla_contingencia)[3]) {
  barplot(tabla_contingencia[,,i], beside = TRUE, legend.text = TRUE, 
          main = paste("Relación entre Género, Conformidad y Tiempo (minutos) (", dimnames(tabla_contingencia)[[3]][i], ")"), 
          xlab = "Nivel de Conformidad", ylab = "Frecuencia",
          col = c("pink", "lightblue"))
}

# Boxplot para analizar tiempo 
bp <- boxplot(as.numeric(dr$`Tiempo que tarda en 1 recorrido (Minutos)`),
  main = "Cajas y Bigotes de tiempo",
  xlab = "Tiempo",
  horizontal = T)

# Mostrar los valores de q1, q2 y q3
q1 <- bp$stats[2]
q2 <- bp$stats[3]
q3 <- bp$stats[4]

# Agregar las etiquetas al gráfico
legend("topright", inset=.05, title="Cuartiles", 
       legend=paste("Q1: ", round(q1, 2), "\nQ2: ", round(q2, 2), "\nQ3: ", round(q3, 2)), cex=1)

#Realizar una tabla de datos agrupados para analizar el nivel de conformidad con respecto al tiempo
# Calcular el número de intervalos (k)
n <- length(as.numeric(dr$`Tiempo que tarda en 1 recorrido (Minutos)`))
k <- ceiling(sqrt(n))

# Calcular el rango de los datos
rango <- max(as.numeric(dr$`Tiempo que tarda en 1 recorrido (Minutos)`)) - min(as.numeric(dr$`Tiempo que tarda en 1 recorrido (Minutos)`))

# Calcular el ancho de cada intervalo
ancho_intervalo <- ceiling(rango / k)

# Calcular los límites de cada intervalo
limites <- seq(min(as.numeric(dr$`Tiempo que tarda en 1 recorrido (Minutos)`)), max(as.numeric(dr$`Tiempo que tarda en 1 recorrido (Minutos)`)), by = ancho_intervalo)

# Crear una columna en el dataframe para asignar el intervalo correspondiente a cada dato
dr$Intervalo <- cut(as.numeric(dr$`Tiempo que tarda en 1 recorrido (Minutos)`), breaks = limites, include.lowest = TRUE)

# Agrupar los datos por intervalo
df_grouped <- group_by(dr, Intervalo)

df_summary <- summarise(df_grouped, Promedio_Conformidad = format(mean(as.numeric(`Nivel de conformidad`)), digits = 3))

# Mostrar el resumen de los promedios de conformidad por intervalo de tiempo
kable(df_summary)

```
